name: Telegram PR Notify

on:
  pull_request:
    types: [opened, closed, reopened]

jobs:
  telegram:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            📌 ${{ github.event.action}} Pull Request
            
            Title: ${{ github.event.pull_request.title }}
            
            Description:

            ${{ github.event.pull_request.body }}
            ----------
            Link: (${{ github.event.pull_request.html_url }})
          parse_mode: markdown