name: Telegram PR Notify

on:
  pull_request:
    types: [closed]

jobs:
  telegram:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Topic Message
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -H "Content-Type: application/json" \
          -d "{
            \"chat_id\": \"${{ secrets.TELEGRAM_CHAT_ID }}\",
            \"message_thread_id\": ${{ secrets.THREAD_ID }},
            \"parse_mode\": \"Markdown\",
            \"text\": \"🕊️ پیک کوچولو از راه رسید\n\nموضوع: ${{ github.event.pull_request.title }}\n\nتوضیحات:\n\n${{ github.event.pull_request.body }}\"
          }"