name: Telegram PR Notify

on:
  pull_request:
    types: [closed]

jobs:
  telegram:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            🕊️ پیک کوچولو از راه رسید

            ⏳ تا قبل از فراموشی انجامش بده
            
            موضوع: ${{ github.event.pull_request.title }}
            
            توضیحات:

            ${{ github.event.pull_request.body }}
          parse_mode: markdown